# SPDX-License-Identifier: MIT

from .analysis import (
    ApplicationLogError,
    ApplicationLogEvent,
    DisconnectAssertion,
    EventCountAssertion,
    KernelWarningAssertion,
    RecoveryLatencyAssertion,
    RecoveryMetrics,
    RecoveryWindow,
    RetryAssertion,
    StdoutAssertion,
    calculate_recovery_metrics,
    evaluate_disconnect,
    evaluate_event_assertions,
    evaluate_kernel_warnings,
    evaluate_recovery_latency,
    evaluate_retry_count,
    evaluate_stdout_assertion,
    parse_application_log,
)
from .scenario import ScenarioDefinition, ScenarioError, ScenarioValidationError, load_scenario
from .report import (
    REPORT_SCHEMA_VERSION,
    ReportStatus,
    ScenarioReport,
    build_error_report,
    build_scenario_report,
)
from .junit import report_to_junit_xml
from .runner import (
    ApplicationProcess,
    ApplicationResult,
    ApplicationTimeoutError,
    DispatchRecord,
    DmesgKernelLogCollector,
    EventDispatchError,
    FaultConfiguration,
    LinuxDeviceBackend,
    KernelLogObservation,
    KernelLogSnapshot,
    RunnerError,
    ScenarioRunner,
    ScenarioRunResult,
    ScenarioScheduler,
)

__all__ = [
    "ApplicationLogError",
    "ApplicationLogEvent",
    "ApplicationProcess",
    "ApplicationResult",
    "ApplicationTimeoutError",
    "ScenarioDefinition",
    "ScenarioScheduler",
    "ScenarioError",
    "ScenarioValidationError",
    "DispatchRecord",
    "DisconnectAssertion",
    "DmesgKernelLogCollector",
    "EventDispatchError",
    "EventCountAssertion",
    "FaultConfiguration",
    "LinuxDeviceBackend",
    "KernelLogObservation",
    "KernelLogSnapshot",
    "KernelWarningAssertion",
    "RecoveryMetrics",
    "RecoveryLatencyAssertion",
    "RecoveryWindow",
    "REPORT_SCHEMA_VERSION",
    "ReportStatus",
    "RetryAssertion",
    "StdoutAssertion",
    "RunnerError",
    "ScenarioRunner",
    "ScenarioRunResult",
    "ScenarioReport",
    "build_error_report",
    "build_scenario_report",
    "calculate_recovery_metrics",
    "evaluate_disconnect",
    "evaluate_event_assertions",
    "evaluate_kernel_warnings",
    "evaluate_recovery_latency",
    "evaluate_retry_count",
    "evaluate_stdout_assertion",
    "load_scenario",
    "parse_application_log",
    "report_to_junit_xml",
]
__version__ = "0.1.0"
